# Generated by Django 6.0.5 on 2026-05-28 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_sql', models.TextField()),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('execution_status', models.CharField(blank=True, default='', max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='exams.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='questions.question')),
            ],
            options={
                'db_table': 'submission',
            },
        ),
    ]
